from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
import json
import os

def react_app(request):
    return render(request, "index.html")

@csrf_exempt
@require_http_methods(["POST"])
def generate_problem(request):
    try:
        data = json.loads(request.body)
        
        topic = data.get('topic', '')
        area_subject = data.get('areaSubject', '')
        grade = data.get('grade', '')
        standards = data.get('standards', '')
        dok = data.get('dok', '')
        difficulty = data.get('difficulty', 'medium')
        language = data.get('language', 'English')
        interest_value = data.get('interestValue', '')
        format_type = data.get('format', '')
        number_of_problems = data.get('numberOfProblems', 1)
        additional_requirements = data.get('additionalRequirements', '')
        selected_tags = data.get('selectedTags', [])
        
        prompt = f"Generate {number_of_problems} math problem(s) about {topic or area_subject}.\n"
        if grade:
            prompt += f"Grade Level: {grade}th grade\n"
        if dok:
            prompt += f"Depth of Knowledge: {dok}\n"
        if difficulty:
            prompt += f"Difficulty: {difficulty}\n"
        if language != 'English':
            prompt += f"Language: {language}\n"
        if interest_value:
            prompt += f"Context: {interest_value}\n"
        if selected_tags:
            prompt += f"Incorporate these interests: {', '.join(selected_tags)}\n"
        if additional_requirements:
            prompt += f"Requirements: {additional_requirements}\n"
        
        prompt += "\nProvide:\n1. Problem statement\n2. Hints\n3. Step-by-step solution\n4. Final answer\n"
        
        # TODO: Replace with actual OpenAI/GPT call
        # from openai import OpenAI
        # client = OpenAI(api_key=os.environ.get('OPENAI_API_KEY'))
        # completion = client.chat.completions.create(
        #     model="gpt-4",
        #     messages=[
        #         {"role": "system", "content": "You are a helpful math tutor."},
        #         {"role": "user", "content": prompt}
        #     ]
        # )
        # response_text = completion.choices[0].message.content
        
        response_data = {
            "problem": f"<p><strong>Problem:</strong> {topic or area_subject}</p><p>Placeholder problem will be generated by GPT API</p>",
            "hints": "<p>Hint 1: Start by identifying what you know</p><p>Hint 2: Break the problem into steps</p>",
            "solution": "<p>Step 1: ...</p><p>Step 2: ...</p>",
            "answer": "<p><strong>Answer: </strong>Placeholder answer</p>"
        }
        
        return JsonResponse(response_data, status=200)
        
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)

@csrf_exempt
@require_http_methods(["GET"])
def health_check(request):
    return JsonResponse({"status": "healthy"})
